#!/bin/bash

# Syntax: build-ls980/build <Optional Fancy Name Here>
# This is a shortcut to build the ls980. It's simple and optimized
# for one system. It is important to run this command from the root of the
# android project source tree.

source build/envsetup.sh
breakfast cm_ls980-userdebug

if [ $? == 0 ]
then
  LOG_FILE=build-log.`date +%FT%T`

  echo '** Starting the build in a screen process...'
  screen -dm build-ls980/setup-build $LOG_FILE $1
  echo '** The build has started. It may be accessed using `screen -rd`'
  sleep 1

  echo '** Now tailing the log file. You may safely interupt at any time'
  echo ''
  echo '*******************************************************************'
  tail -fn 0 $LOG_FILE
fi