#!/bin/bash

. build/envsetup.sh
breakfast cm_ls980-userdebug
if [ $# -ne 0 ]
then
  export CM_BUILDTYPE="EXPERIMENTAL"
  export CM_EXTRAVERSION=$1
fi

LOG_FILE=build-log.`date +%FT%T`
( time mka bacon -j8 >&$LOG_FILE ) 2>>$LOG_FILE